# Auto-generated by FS scenario reduction
# Fields per scenario: id, kind, kind_code, fail1, fail2, p, orig_index

scenario_defs = [
    {
        'id': 4,
        'kind': 'Scattered',
        'kind_code': 'D',
        'fail1': [
            (1, 2), (7, 8), (8, 13), (12, 17), (13, 18), (17, 22), (19, 24)
        ],
        'fail2': [
            (1, 6), (6, 7), (11, 12), (24, 29)
        ],
        'p': 0.083,
        'orig_index': 3
    },
    {
        'id': 36,
        'kind': 'Scattered',
        'kind_code': 'D',
        'fail1': [
(1, 6)            ,
            (2, 3)            ,
            (5, 10)            ,
            (7, 8)            ,
            (8, 13)            ,
            (9, 14)            ,
            (10, 15)            ,
            (12, 17)            ,
            (13, 18)            ,
            (14, 19)            ,
            (20, 25)            ,
            (22, 27)
        ],
        'fail2': [
            (1, 2), (5, 6), (6, 7), (11, 12)
        ],
        'p': 0.340,
        'orig_index': 35
    },
    {
        'id': 133,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (11, 16), (16, 21), (21, 26)
        ],
        'fail2': [
            (6, 11), (11, 12)
        ],
        'p': 0.287,
        'orig_index': 132
    },
    {
        'id': 161,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (6, 11), (11, 12), (11, 16), (16, 21)
        ],
        'fail2': [
            (1, 6), (5, 6), (6, 7), (12, 17), (21, 26)
        ],
        'p': 0.117,
        'orig_index': 160
    },
    {
        'id': 249,
        'kind': 'Hybrid',
        'kind_code': 'M',
        'fail1': [
            (1, 2), (2, 3), (3, 4)
        ],
        'fail2': [
(1, 6)            ,
            (5, 10)            ,
            (6, 11)            ,
            (7, 8)            ,
            (8, 9)            ,
            (8, 13)            ,
            (10, 15)            ,
            (11, 12)            ,
            (14, 19)            ,
            (16, 21)            ,
            (20, 25)
        ],
        'p': 0.173,
        'orig_index': 248
    },
]
