# Auto-generated by FS scenario reduction
# Fields per scenario: id, kind, kind_code, fail1, fail2, p, orig_index

scenario_defs = [
    {
        'id': 93,
        'kind': 'Scattered',
        'kind_code': 'D',
        'fail1': [
(0, 1)            ,
            (2, 3)            ,
            (3, 4)            ,
            (6, 7)            ,
            (6, 11)            ,
            (8, 9)            ,
            (9, 14)            ,
            (10, 11)            ,
            (11, 12)            ,
            (15, 20)            ,
            (17, 22)            ,
            (22, 23)            ,
            (22, 27)
        ],
        'fail2': [
            (5, 6), (11, 16), (16, 17), (27, 28)
        ],
        'p': 0.390,
        'orig_index': 92
    },
    {
        'id': 123,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (17, 22), (22, 23), (22, 27), (27, 28)
        ],
        'fail2': [
            (16, 17), (23, 28), (28, 29)
        ],
        'p': 0.227,
        'orig_index': 122
    },
    {
        'id': 126,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (20, 25), (25, 26)
        ],
        'fail2': [
            (15, 20)
        ],
        'p': 0.097,
        'orig_index': 125
    },
    {
        'id': 128,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (6, 11), (10, 11), (11, 12), (11, 16), (16, 17), (16, 21)
        ],
        'fail2': [
            (5, 6), (6, 7), (8, 12), (10, 15), (12, 13), (17, 22)
        ],
        'p': 0.113,
        'orig_index': 127
    },
    {
        'id': 282,
        'kind': 'Hybrid',
        'kind_code': 'M',
        'fail1': [
            (0, 5), (5, 6), (6, 7), (6, 11)
        ],
        'fail2': [
(0, 1)            ,
            (8, 12)            ,
            (12, 13)            ,
            (13, 14)            ,
            (15, 20)            ,
            (16, 21)            ,
            (17, 22)            ,
            (20, 25)            ,
            (23, 28)            ,
            (24, 29)            ,
            (27, 28)            ,
            (28, 29)
        ],
        'p': 0.173,
        'orig_index': 281
    },
]
