# Auto-generated by FS scenario reduction
# Fields per scenario: id, kind, kind_code, fail1, fail2, p, orig_index

scenario_defs = [
    {
        'id': 92,
        'kind': 'Scattered',
        'kind_code': 'D',
        'fail1': [
(0, 1)            ,
            (1, 2)            ,
            (4, 9)            ,
            (7, 12)            ,
            (8, 13)            ,
            (10, 15)            ,
            (11, 12)            ,
            (11, 16)            ,
            (13, 18)            ,
            (16, 21)            ,
            (20, 21)            ,
            (24, 28)            ,
            (24, 29)
        ],
        'fail2': [
            (2, 7), (18, 23), (19, 24), (21, 26)
        ],
        'p': 0.377,
        'orig_index': 91
    },
    {
        'id': 130,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (7, 12), (8, 13), (11, 12), (12, 13), (12, 17), (13, 18)
        ],
        'fail2': [
            (2, 7), (11, 16), (17, 22), (18, 19), (18, 23)
        ],
        'p': 0.127,
        'orig_index': 129
    },
    {
        'id': 143,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (16, 21), (20, 21), (21, 26)
        ],
        'fail2': [
            (11, 16), (15, 20), (20, 25)
        ],
        'p': 0.217,
        'orig_index': 142
    },
    {
        'id': 153,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (0, 1), (0, 5)
        ],
        'fail2': [
            (1, 2), (1, 6)
        ],
        'p': 0.120,
        'orig_index': 152
    },
    {
        'id': 289,
        'kind': 'Hybrid',
        'kind_code': 'M',
        'fail1': [
            (1, 2), (2, 3), (2, 7), (7, 12)
        ],
        'fail2': [
(0, 5)            ,
            (8, 13)            ,
            (10, 15)            ,
            (11, 16)            ,
            (12, 17)            ,
            (15, 20)            ,
            (17, 22)            ,
            (18, 19)            ,
            (20, 25)            ,
            (24, 29)            ,
            (28, 29)
        ],
        'p': 0.160,
        'orig_index': 288
    },
]
