# Auto-generated by FS scenario reduction
# Fields per scenario: id, kind, kind_code, fail1, fail2, p, orig_index

scenario_defs = [
    {
        'id': 105,
        'kind': 'Scattered',
        'kind_code': 'D',
        'fail1': [
(1, 2)            ,
            (7, 12)            ,
            (8, 9)            ,
            (8, 13)            ,
            (12, 13)            ,
            (13, 19)            ,
            (15, 16)            ,
            (17, 22)            ,
            (18, 24)            ,
            (24, 29)            ,
            (26, 27)
        ],
        'fail2': [
            (0, 1), (12, 17), (13, 18), (16, 21)
        ],
        'p': 0.377,
        'orig_index': 104
    },
    {
        'id': 123,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (16, 21), (20, 21), (20, 25)
        ],
        'fail2': [
            (11, 16), (15, 16)
        ],
        'p': 0.137,
        'orig_index': 122
    },
    {
        'id': 153,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (2, 7), (6, 7), (7, 12), (11, 12), (12, 13), (12, 17)
        ],
        'fail2': [
            (1, 2), (8, 13), (11, 16), (13, 18), (13, 19), (17, 22)
        ],
        'p': 0.137,
        'orig_index': 152
    },
    {
        'id': 168,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (1, 2), (2, 7), (6, 7), (7, 12)
        ],
        'fail2': [
            (0, 1), (11, 12), (12, 13), (12, 17)
        ],
        'p': 0.167,
        'orig_index': 167
    },
    {
        'id': 271,
        'kind': 'Hybrid',
        'kind_code': 'M',
        'fail1': [
            (3, 8), (8, 9), (8, 13), (9, 14)
        ],
        'fail2': [
(1, 2)            ,
            (2, 7)            ,
            (6, 7)            ,
            (11, 12)            ,
            (11, 16)            ,
            (12, 13)            ,
            (14, 19)            ,
            (15, 16)            ,
            (17, 22)            ,
            (20, 21)
        ],
        'p': 0.183,
        'orig_index': 270
    },
]
