# Auto-generated by FS scenario reduction
# Fields per scenario: id, kind, kind_code, fail1, fail2, p, orig_index

scenario_defs = [
    {
        'id': 19,
        'kind': 'Scattered',
        'kind_code': 'D',
        'fail1': [
            (0, 4), (1, 10), (2, 12), (5, 9), (5, 11), (8, 9), (8, 12)
        ],
        'fail2': [
            (0, 11), (3, 4), (3, 8), (6, 10), (9, 10)
        ],
        'p': 0.207,
        'orig_index': 18
    },
    {
        'id': 121,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (2, 12), (3, 8), (4, 8), (8, 9), (8, 12)
        ],
        'fail2': [
            (0, 4), (2, 10), (3, 4), (4, 5), (5, 9), (9, 10)
        ],
        'p': 0.243,
        'orig_index': 120
    },
    {
        'id': 122,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (1, 10), (2, 10), (5, 9), (6, 10), (8, 9), (9, 10)
        ],
        'fail2': [
            (1, 7), (2, 12), (3, 8), (4, 5), (4, 8), (5, 6), (5, 11), (6, 7), (8, 12)
        ],
        'p': 0.107,
        'orig_index': 121
    },
    {
        'id': 137,
        'kind': 'Regional',
        'kind_code': 'R',
        'fail1': [
            (0, 11), (4, 5), (5, 6), (5, 9), (5, 11), (7, 11)
        ],
        'fail2': [
            (0, 4), (1, 7), (3, 4), (4, 8), (6, 7), (6, 10), (8, 9), (9, 10)
        ],
        'p': 0.180,
        'orig_index': 136
    },
    {
        'id': 249,
        'kind': 'Hybrid',
        'kind_code': 'M',
        'fail1': [
            (0, 11), (4, 5), (5, 6), (5, 9), (5, 11), (7, 11)
        ],
        'fail2': [
            (0, 4), (1, 7), (1, 10), (4, 8), (6, 10)
        ],
        'p': 0.263,
        'orig_index': 248
    },
]
